# Generated by Django 3.0.2 on 2020-01-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifyCodeModel',
            new_name='CaptchaModel',
        ),
    ]
