# Generated by Django 3.0.2 on 2020-03-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='photo',
            new_name='avatar',
        ),
    ]
