# Generated by Django 3.0.2 on 2020-03-13 12:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200310_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='face_128d_features',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar/', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='users/face_photo/', verbose_name='人脸照片')),
                ('face_128d_features', models.TextField(verbose_name='人脸128D数据')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户详情信息',
                'verbose_name_plural': '用户详情信息',
            },
        ),
    ]
