# Generated by Django 3.0.2 on 2020-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200313_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userface',
            old_name='face_photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='userface',
            name='face_128d_features',
        ),
        migrations.AddField(
            model_name='userface',
            name='features',
            field=models.TextField(default=1, verbose_name='特征数据'),
            preserve_default=False,
        ),
    ]
