# Generated by Django 3.0.1 on 2020-01-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200101_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='realname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
