# Generated by Django 3.0.2 on 2020-02-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200201_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓名'),
        ),
    ]
