# Generated by Django 3.0.2 on 2020-03-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0009_auto_20200321_1053'),
        ('users', '0007_auto_20200317_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lived_dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lived_users', to='dormitories.Dormitory', verbose_name='居住宿舍'),
        ),
    ]
