# Generated by Django 3.0.2 on 2020-04-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0011_auto_20200322_1412'),
        ('users', '0008_auto_20200321_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lived_dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lived_users', to='dormitories.Dormitory', verbose_name='居住宿舍'),
        ),
    ]
