# Generated by Django 3.0.2 on 2020-02-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='1.jpg', null=True, upload_to='users/photo/', verbose_name='照片'),
        ),
    ]
