# Generated by Django 3.0.2 on 2020-05-06 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_qqlogintokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqlogintokenmodel',
            name='openid',
            field=models.CharField(default=1, max_length=32, verbose_name='用户OpenID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qqlogintokenmodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 22, 52, 19, 882016), verbose_name='更新日期'),
        ),
    ]
