# Generated by Django 3.0.2 on 2020-03-02 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterRateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('add', '加'), ('sub', '减')], default='sub', max_length=3, verbose_name='操作方式')),
                ('change_water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='改变水量(吨)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_rate_log_dormitory', to='dormitories.Dormitory', verbose_name='宿舍')),
            ],
            options={
                'verbose_name': '宿舍水费使用记录',
                'verbose_name_plural': '宿舍水费使用记录',
            },
        ),
    ]
