# Generated by Django 3.0.2 on 2020-03-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_repair_repairlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairlog',
            name='reply_type',
            field=models.CharField(choices=[('complete', '已完成'), ('processing', '处理中')], default='processing', max_length=10, verbose_name='回复类型'),
        ),
    ]
