# Generated by Django 3.0.2 on 2020-03-15 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitories', '0008_auto_20200305_2205'),
        ('user_operation', '0006_auto_20200315_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterRateFeesLog',
            new_name='WaterFeesLog',
        ),
    ]
