# Generated by Django 3.0.2 on 2020-04-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0011_auto_20200322_1412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0008_auto_20200321_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesRechargeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='充值金额(元)')),
                ('recharge_object', models.CharField(choices=[('water', '水费'), ('electricity', '电费')], default='water', max_length=11, verbose_name='充值对象')),
                ('recharge_type', models.CharField(choices=[('alipay', '支付宝'), ('qpay', 'QQ钱包'), ('wechar', '微信')], default='alipay', max_length=6, verbose_name='充值方式')),
                ('recharge_status', models.CharField(choices=[('success', '充值成功'), ('closed', '超时关闭'), ('paying', '待支付')], default='paying', max_length=7, verbose_name='充值状态')),
                ('pay_id', models.CharField(max_length=100, verbose_name='充值订单号')),
                ('pay_no', models.CharField(max_length=100, verbose_name='充值流水号(支付平台订单号)')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_recharge_order_s_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('recharge_dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_recharge_order_s_dormitory', to='dormitories.Dormitory', verbose_name='宿舍')),
            ],
            options={
                'verbose_name': '充值订单记录',
                'verbose_name_plural': '充值订单记录',
            },
        ),
    ]
