# Generated by Django 3.0.2 on 2020-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0009_feesrechargeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesrechargeorder',
            name='pay_no',
            field=models.CharField(max_length=100, null=True, verbose_name='充值流水号(支付平台订单号)'),
        ),
    ]
