# Generated by Django 3.0.2 on 2020-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0011_auto_20200429_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesrechargeorder',
            name='recharge_number',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='充值数量'),
            preserve_default=False,
        ),
    ]
