# Generated by Django 3.0.2 on 2020-04-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0012_feesrechargeorder_recharge_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesrechargeorder',
            name='price',
            field=models.IntegerField(verbose_name='充值金额(元)'),
        ),
    ]
