# Generated by Django 3.0.2 on 2020-05-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0013_auto_20200429_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesrechargeorder',
            name='pay_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='充值流水号(支付平台订单号)'),
        ),
    ]
