# Generated by Django 3.0.2 on 2020-03-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='代码')),
                ('title', models.CharField(max_length=10, verbose_name='标题')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('url', models.CharField(max_length=100, verbose_name='链接')),
                ('note', models.CharField(max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
