# Generated by Django 3.0.2 on 2020-03-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='note',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='链接'),
        ),
    ]
