# Generated by Django 3.0.2 on 2020-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0003_auto_20200304_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='code',
            field=models.CharField(max_length=20, verbose_name='代码'),
        ),
    ]
