# Generated by Django 3.0.2 on 2020-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0004_auto_20200304_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='url',
            field=models.FileField(null=True, upload_to='media/file/', verbose_name='链接'),
        ),
    ]
