# Generated by Django 3.0.2 on 2020-03-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0005_auto_20200328_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='content',
        ),
    ]
