# Generated by Django 3.0.2 on 2020-03-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0006_remove_systemsetting_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='content',
            field=models.TextField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
