# Generated by Django 3.0.2 on 2020-04-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0007_systemsetting_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='code',
            field=models.CharField(max_length=50, verbose_name='代码'),
        ),
    ]
