# Generated by Django 3.0.2 on 2020-05-05 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_setting', '0008_auto_20200406_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='操作内容')),
                ('category', models.CharField(max_length=10, verbose_name='操作种类')),
                ('ip', models.CharField(max_length=100, verbose_name='操作IP')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_log_s_operator', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
            },
        ),
    ]
