# Generated by Django 3.0.2 on 2020-05-06 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0010_auto_20200505_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 13, 18, 57, 984789), verbose_name='操作时间'),
        ),
    ]
