# Generated by Django 3.0.2 on 2020-05-06 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0011_systemlog_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='操作内容'),
        ),
    ]
