# Generated by Django 3.0.2 on 2020-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterrate',
            name='surplus_water',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='剩余水量(吨)'),
            preserve_default=False,
        ),
    ]
