# Generated by Django 3.0.2 on 2020-03-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0003_waterrate_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterrate',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='水费(元/吨)'),
            preserve_default=False,
        ),
    ]
