# Generated by Django 3.0.2 on 2020-03-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0005_electricityfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityfees',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
    ]
