# Generated by Django 3.0.2 on 2020-03-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0006_electricityfees_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityfees',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
