# Generated by Django 3.0.2 on 2020-03-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0007_auto_20200304_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='已用水量(吨)')),
                ('surplus_water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='剩余水量(吨)')),
                ('total_water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='总共水量(吨)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='水费(元/吨)')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('month', models.DateField(verbose_name='月份')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_fees_dormitory', to='dormitories.Dormitory', verbose_name='宿舍')),
            ],
            options={
                'verbose_name': '宿舍水费',
                'verbose_name_plural': '宿舍水费',
            },
        ),
        migrations.DeleteModel(
            name='WaterRate',
        ),
    ]
