# Generated by Django 3.0.2 on 2020-03-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0009_auto_20200321_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterfees',
            old_name='have_electricity_fees',
            new_name='have_water_fees',
        ),
    ]
