# Generated by Django 3.0.2 on 2020-03-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0010_auto_20200321_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityfees',
            name='dormitory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_fees', to='dormitories.Dormitory', verbose_name='宿舍'),
        ),
        migrations.AlterField(
            model_name='electricityfees',
            name='have_electricity_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='现有金额(元)'),
        ),
        migrations.AlterField(
            model_name='waterfees',
            name='dormitory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_fees', to='dormitories.Dormitory', verbose_name='宿舍'),
        ),
        migrations.AlterField(
            model_name='waterfees',
            name='have_water_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='现有金额(元)'),
        ),
    ]
