# Generated by Django 3.0.2 on 2020-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0011_auto_20200322_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
