# Generated by Django 3.0.2 on 2020-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='state',
            field=models.CharField(choices=[('normal', '正常'), ('later', '晚归'), ('abnormal', '异常')], default='normal', max_length=10, verbose_name='状态'),
        ),
    ]
