# Generated by Django 3.0.2 on 2020-03-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_accesscontrol_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesscontrol',
            old_name='state',
            new_name='status',
        ),
    ]
