# Generated by Django 3.0.2 on 2020-03-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_auto_20200322_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='status',
            field=models.CharField(choices=[('normal', '识别正常'), ('later', '学生晚归'), ('abnormal', '识别异常')], default='normal', max_length=10, verbose_name='状态'),
        ),
    ]
