# Generated by Django 3.0.2 on 2020-03-24 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_control', '0004_auto_20200323_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='status',
            field=models.CharField(choices=[('normal', '识别正常'), ('later', '学生晚归'), ('abnormal', '识别异常')], default='normal', max_length=8, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='AccessControlAbnormalApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', '待处理'), ('pass', '通过'), ('fail', '未通过')], default='pending', max_length=7, verbose_name='结果')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('application_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_abnormal_application_s_application_person', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('main_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_abnormal_application_s_main_record', to='access_control.AccessControl', verbose_name='主记录')),
            ],
            options={
                'verbose_name': '门禁记录 识别异常 申请',
                'verbose_name_plural': '门禁记录 识别异常 申请',
            },
        ),
    ]
