# Generated by Django 3.0.2 on 2020-03-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_auto_20200324_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolabnormalapplication',
            name='main_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_abnormal_application_s_main_record', to='access_control.AccessControl', verbose_name='主记录'),
        ),
    ]
