# Generated by Django 3.0.2 on 2020-03-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_auto_20200324_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrolabnormalapplication',
            name='content',
            field=models.TextField(default=1, verbose_name='申请内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesscontrolabnormalapplication',
            name='main_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_application', to='access_control.AccessControl', verbose_name='主记录'),
        ),
    ]
