# Generated by Django 3.0.2 on 2020-05-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_auto_20200325_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
